[package]
name = "ring-rs"
version = "0.0.0"
authors = ["luncj <jialun.tsai@gmail.com>"]
repository = "https://github.com/luncj/ring-rs"
description = "consistent hashing with bounded loads"
license = "MIT"
edition = "2018"

[dependencies]
blake2 = "0.8"
byteorder = "1"
